[package]
name = "test_contract"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
fracpack = { version = "0.1.0", path = "../fracpack" }
psibase = { version = "0.1.0", path = "../psibase" }
