[package]
name = "libpsibase"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
custom_error = "1.9"
fracpack = { version = "0.1.0", path = "../fracpack" }
libpsibase_names = { version = "0.1.0", path = "../libpsibase_names" }
psi_macros = { version = "0.1.0", path = "../psi_macros" }
reqwest = { version = "0.11", features = ["json"] }
ripemd = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
