[package]
name = "libpsibase"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
custom_error = "1.9"
fracpack = { version = "0.1.0", path = "../fracpack" }
libpsibase_names = { version = "0.1.0", path = "../libpsibase_names" }
psi_macros = { version = "0.1.0", path = "../psi_macros" }
ripemd = "0.1"
serde = { version = "1.0", features = ["derive"] }
