[package]
name = "psibase"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = {version = "3.1", features = ["derive"]}
custom_error = "1.9"
fracpack = { version = "0.1.0", path = "../fracpack" }
futures = "0.3"
include_dir = "0.7"
indicatif = "0.17"
libpsibase = { version = "0.1.0", path = "../libpsibase" }
mime_guess = "2.0"
reqwest = { version = "0.11", default-features = false, features = ["json","rustls-tls"] }
secp256k1 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
cxx-build = "1.0"
