[package]
name = "psibase"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = {version = "3.1", features = ["derive"]}
custom_error = "1.9"
fracpack = { version = "0.1.0", path = "../fracpack" }
futures = "0.3"
include_dir = "0.7"
indicatif = "0.17"
mime_guess = "2.0"
psibase_macros = { version = "0.1.0", path = "../psibase_macros" }
psibase_names = { version = "0.1.0", path = "../psibase_names" }
reqwest = { version = "0.11", default-features = false, features = ["json","rustls-tls"] }
ripemd = "0.1"
secp256k1 = { version="0.22", features = ["global-context", "bitcoin_hashes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
